EdicoesEmMassa/Controllers/DashboardController.cs
using EdicoesEmMassa.Model;
using EdicoesEmMassa.Repository;
using EdicoesEmMassa.Service;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading;

namespace EdicoesEmMassa.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardService _DashboardService;


        public DashboardController(IDashboardService dashboardService)
        {
            _DashboardService = dashboardService;
        }

        public IActionResult Index()
        {
            return View(_DashboardService.GetDataForDashboard());
        }
    }
}

EdicoesEmMassa/Controllers/IncubadoraController.cs
using EdicoesEmMassa.Model;
using EdicoesEmMassa.Repository;
using EdicoesEmMassa.Service;
using Microsoft.AspNetCore.Mvc;

namespace EdicoesEmMassa.Controllers
{
    public class IncubadoraController : Controller
    {
        private readonly IIncubatorService _incubatorService;

        public IncubadoraController(IIncubatorService incubatorService)
        {
            _incubatorService = incubatorService;
        }
        public IActionResult Index()
        {
            var Incubadoras = _incubatorService.GetAll();
            return View(Incubadoras);
        }

        public IActionResult Creating()
        {
            return View();
        }

        public IActionResult Update(int id)
        {
            var Incubadora = _incubatorService.GetById(id);
            return View(Incubadora);
        }

        public IActionResult ConfirmDelete(int id)
        {
            var Incubadora = _incubatorService.GetById(id);
            return View(Incubadora);
        }
        public IActionResult Delete(int id)
        {

            _incubatorService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Creating(Incubadora Incubadora)
        {

            if (ModelState.IsValid)
            {
                _incubatorService.Creating(Incubadora);
                return RedirectToAction("Index");
            }

            return View(Incubadora);

        }

        [HttpPost]
        public IActionResult Update(Incubadora Incubadora)
        {
            if (ModelState.IsValid)
            {
                _incubatorService.Update(Incubadora);
                return RedirectToAction("Index");
            }

            return View(Incubadora);
        }
    }
}

EdicoesEmMassa/Controllers/RelatorioController.cs
using EdicoesEmMassa.Repository;
using EdicoesEmMassa.Service;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EdicoesEmMassa.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly IRelatorioService _TemperaturaRepository;


        public RelatorioController(IRelatorioService temperaturaRepository)
        {
            _TemperaturaRepository = temperaturaRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreatePDF()
        {
            _TemperaturaRepository.DeserializeTemperatura();
            return RedirectToAction("Index", "Dashboard");
        }
    }
}

EdicoesEmMassa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Temperatura</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">;
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Incubadora" asp-action="Index">Cadastro de Incubadoras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Relatorio" asp-action="Index">Relatórios</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle de Temperatura
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EdicoesEmMassa/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Temperatura</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="rodape">
            &copy; 2022 - Controle de Temperatura
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>